---
title: "Adapting nf-core/chipseq to run on nih biowulf"
author: "Brian Capaldo"
date: "2/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Obtain the workflow

Nextflow is a great tool for running complex bioinformatics pipelines and is well designed to work with resources at the NIH (and most other research institutions). Additionally, there is a host of nextflow community generated pipelines for widespread use and adoption. Among the groups is the NF Core group, which seeks to produce and maintain best practice pipelines for bioinformatics analysis. The end goal is that each of these pipelines can be run as easily as most bioinformatics command line tools leveraging docker and or singularity to handle the software in the backend. However, docker does not work on biowulf, and I've had multiple issues with getting the singularity containers to run consistently. Towards this end, I'm composing this guide to create a local only version of the nextflow core pipelines, starting with the ChiP Seq pipeline. Nextflow supports slurm, the job executor used by biowulf, and the use of modules, which is how biowulf handles loading software. First, we want to fork the nf-core/chipseq directory to the lgcp github. Rstudio was used to grab the repo and clone it locally. 

# Change configuration files

The primary goal is to edit or add a configuration file such that the nf-core/chipseq workflow will run on biowulf. In the past, we built out a nextflow pipeline and created a basic config file, we're going to start with that here, and work from there. We manually edited "uppmax-modules.config" with the working version of the biowulf config file. Additionally, python is confusing to run on biowulf, and phantompeakqualtools is not available, so we will be skipping those steps in the workflow. We also commented out processes in main.nf that wouldn't run, as well as added biowulf as a profile in the nextflow.config file.

